"""Store the site's own level, experience and work-mode tags

Revision ID: 2b9e1f5fdf51
Revises: edc3cff48150
Create Date: 2026-09-08 09:19:28.577301
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2b9e1f5fdf51"
down_revision: str | None = "edc3cff48150"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("level_raw", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("experience_raw", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("work_mode_raw", sa.String(length=200), nullable=True))
        batch_op.add_column(
            sa.Column("languages_raw", sa.JSON(), nullable=False, server_default="[]")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("languages_raw")
        batch_op.drop_column("work_mode_raw")
        batch_op.drop_column("experience_raw")
        batch_op.drop_column("level_raw")

    # ### end Alembic commands ###
