"""initial schema

Revision ID: d8505cc8ab9c
Revises:
Create Date: 2026-09-07 12:31:36.779780
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d8505cc8ab9c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("jobs_seen", sa.Integer(), nullable=False),
        sa.Column("jobs_new", sa.Integer(), nullable=False),
        sa.Column("jobs_updated", sa.Integer(), nullable=False),
        sa.Column("jobs_classified", sa.Integer(), nullable=False),
        sa.Column("jobs_matched", sa.Integer(), nullable=False),
        sa.Column("applications_submitted", sa.Integer(), nullable=False),
        sa.Column("errors_count", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_runs")),
    )
    with op.batch_alter_table("automation_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_automation_runs_status"), ["status"], unique=False)

    op.create_table(
        "candidate_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=300), nullable=True),
        sa.Column("phone", sa.String(length=60), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("years_experience", sa.Float(), nullable=False),
        sa.Column("desired_seniority", sa.String(length=20), nullable=False),
        sa.Column("preferred_locations", sa.JSON(), nullable=False),
        sa.Column("remote_ok", sa.Boolean(), nullable=False),
        sa.Column("education", sa.JSON(), nullable=False),
        sa.Column("languages", sa.JSON(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("frameworks", sa.JSON(), nullable=False),
        sa.Column("databases", sa.JSON(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("soft_skills", sa.JSON(), nullable=False),
        sa.Column("employment_types", sa.JSON(), nullable=False),
        sa.Column("salary_expectation_min", sa.Float(), nullable=True),
        sa.Column("salary_expectation_max", sa.Float(), nullable=True),
        sa.Column("salary_currency", sa.String(length=10), nullable=False),
        sa.Column("portfolio_url", sa.String(length=500), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("github_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_profile")),
    )
    with op.batch_alter_table("candidate_profile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_profile_is_active"), ["is_active"], unique=False
        )

    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("source_company_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_companies_normalized_name"), ["normalized_name"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_companies_source_company_id"), ["source_company_id"], unique=False
        )

    op.create_table(
        "cv_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("text_extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cv_files")),
        sa.UniqueConstraint("path", name="uq_cv_files_path"),
    )
    with op.batch_alter_table("cv_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cv_files_language"), ["language"], unique=False)

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_job_id", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("normalized_url", sa.String(length=1000), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("title_normalized", sa.String(length=500), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("company_name_raw", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_hash", sa.String(length=64), nullable=True),
        sa.Column("location_raw", sa.String(length=300), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("work_mode", sa.String(length=20), nullable=False),
        sa.Column("salary_min", sa.Float(), nullable=True),
        sa.Column("salary_max", sa.Float(), nullable=True),
        sa.Column("salary_currency", sa.String(length=10), nullable=True),
        sa.Column("salary_period", sa.String(length=20), nullable=True),
        sa.Column("salary_raw", sa.String(length=300), nullable=True),
        sa.Column("employment_type", sa.String(length=20), nullable=False),
        sa.Column("seniority", sa.String(length=20), nullable=False),
        sa.Column("seniority_confidence", sa.Float(), nullable=False),
        sa.Column("seniority_signals", sa.JSON(), nullable=False),
        sa.Column("is_it", sa.Boolean(), nullable=True),
        sa.Column("it_confidence", sa.Float(), nullable=False),
        sa.Column("it_signals", sa.JSON(), nullable=False),
        sa.Column("location_relevant", sa.Boolean(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("tech_keywords", sa.JSON(), nullable=False),
        sa.Column("requirements_required", sa.JSON(), nullable=False),
        sa.Column("requirements_preferred", sa.JSON(), nullable=False),
        sa.Column("years_experience_required", sa.Float(), nullable=True),
        sa.Column("application_method", sa.String(length=30), nullable=False),
        sa.Column("application_url", sa.String(length=1000), nullable=True),
        sa.Column("application_email", sa.String(length=300), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("state_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_at_raw", sa.String(length=100), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column("detail_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_jobs_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("fingerprint", name="uq_jobs_fingerprint"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_city"), ["city"], unique=False)
        batch_op.create_index(
            "ix_jobs_company_title", ["company_id", "title_normalized"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_jobs_description_hash"), ["description_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_jobs_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_is_archived"), ["is_archived"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_is_it"), ["is_it"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_location_relevant"), ["location_relevant"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_jobs_normalized_url"), ["normalized_url"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_jobs_seniority"), ["seniority"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_source_job_id"), ["source_job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_state"), ["state"], unique=False)
        batch_op.create_index("ix_jobs_state_score", ["state"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_title_normalized"), ["title_normalized"], unique=False
        )

    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("cv_file_id", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("cover_letter_language", sa.String(length=10), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("confirmation_evidence", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("screenshot_path", sa.String(length=1000), nullable=True),
        sa.Column("is_manual", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cv_file_id"],
            ["cv_files.id"],
            name=op.f("fk_applications_cv_file_id_cv_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_applications_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("job_id", name="uq_applications_job_id"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_applications_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_state"), ["state"], unique=False)

    op.create_table(
        "errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("screenshot_path", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_errors_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["automation_runs.id"],
            name=op.f("fk_errors_run_id_automation_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_errors")),
    )
    with op.batch_alter_table("errors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_errors_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_errors_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_errors_run_id"), ["run_id"], unique=False)

    op.create_table(
        "job_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("recommendation", sa.String(length=20), nullable=False),
        sa.Column("strengths", sa.JSON(), nullable=False),
        sa.Column("missing_skills", sa.JSON(), nullable=False),
        sa.Column("disqualifiers", sa.JSON(), nullable=False),
        sa.Column("component_scores", sa.JSON(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_matches_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_matches")),
    )
    with op.batch_alter_table("job_matches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_matches_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_job_matches_recommendation"), ["recommendation"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_job_matches_score"), ["score"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_notifications_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_kind"), ["kind"], unique=False)

    op.create_table(
        "application_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("from_state", sa.String(length=20), nullable=True),
        sa.Column("to_state", sa.String(length=20), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_events_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_application_events_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_events")),
    )
    with op.batch_alter_table("application_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_application_events_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_application_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_application_events_job_id"), ["job_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_events_job_id"))
        batch_op.drop_index(batch_op.f("ix_application_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_application_events_application_id"))

    op.drop_table("application_events")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_kind"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("job_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_matches_score"))
        batch_op.drop_index(batch_op.f("ix_job_matches_recommendation"))
        batch_op.drop_index(batch_op.f("ix_job_matches_job_id"))

    op.drop_table("job_matches")
    with op.batch_alter_table("errors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_errors_run_id"))
        batch_op.drop_index(batch_op.f("ix_errors_created_at"))
        batch_op.drop_index(batch_op.f("ix_errors_category"))

    op.drop_table("errors")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_state"))
        batch_op.drop_index(batch_op.f("ix_applications_job_id"))

    op.drop_table("applications")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_title_normalized"))
        batch_op.drop_index("ix_jobs_state_score")
        batch_op.drop_index(batch_op.f("ix_jobs_state"))
        batch_op.drop_index(batch_op.f("ix_jobs_source_job_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_source"))
        batch_op.drop_index(batch_op.f("ix_jobs_seniority"))
        batch_op.drop_index(batch_op.f("ix_jobs_normalized_url"))
        batch_op.drop_index(batch_op.f("ix_jobs_location_relevant"))
        batch_op.drop_index(batch_op.f("ix_jobs_is_it"))
        batch_op.drop_index(batch_op.f("ix_jobs_is_archived"))
        batch_op.drop_index(batch_op.f("ix_jobs_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_jobs_description_hash"))
        batch_op.drop_index("ix_jobs_company_title")
        batch_op.drop_index(batch_op.f("ix_jobs_city"))

    op.drop_table("jobs")
    op.drop_table("settings")
    with op.batch_alter_table("cv_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cv_files_language"))

    op.drop_table("cv_files")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_source_company_id"))
        batch_op.drop_index(batch_op.f("ix_companies_normalized_name"))

    op.drop_table("companies")
    with op.batch_alter_table("candidate_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_profile_is_active"))

    op.drop_table("candidate_profile")
    with op.batch_alter_table("automation_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_runs_status"))

    op.drop_table("automation_runs")
    # ### end Alembic commands ###
