"""Add job_evaluations, user_feedback, candidate_preferences

Revision ID: edc3cff48150
Revises: d8505cc8ab9c
Create Date: 2026-09-08 08:29:20.767710
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "edc3cff48150"
down_revision: str | None = "d8505cc8ab9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(length=40), nullable=False),
        sa.Column("value", sa.String(length=120), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("applies", sa.Integer(), nullable=False),
        sa.Column("skips", sa.Integer(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_preferences")),
        sa.UniqueConstraint("dimension", "value", name="uq_candidate_preferences_dim_value"),
    )
    with op.batch_alter_table("candidate_preferences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_preferences_dimension"), ["dimension"], unique=False
        )

    op.create_table(
        "job_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("is_it_role", sa.Boolean(), nullable=True),
        sa.Column("seniority", sa.String(length=20), nullable=False),
        sa.Column("seniority_reasoning", sa.Text(), nullable=True),
        sa.Column("location_fit", sa.String(length=20), nullable=True),
        sa.Column("location_reasoning", sa.Text(), nullable=True),
        sa.Column("employment_fit", sa.Boolean(), nullable=True),
        sa.Column("experience_fit", sa.String(length=20), nullable=True),
        sa.Column("mandatory_requirements", sa.JSON(), nullable=False),
        sa.Column("nice_to_have_requirements", sa.JSON(), nullable=False),
        sa.Column("major_strengths", sa.JSON(), nullable=False),
        sa.Column("major_risks", sa.JSON(), nullable=False),
        sa.Column("rank_score", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("prompt_version", sa.String(length=80), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("job_content_hash", sa.String(length=64), nullable=True),
        sa.Column("candidate_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("degraded_reason", sa.String(length=300), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_evaluations_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_evaluations")),
    )
    with op.batch_alter_table("job_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_evaluations_cache",
            [
                "job_content_hash",
                "candidate_fingerprint",
                "model",
                "prompt_version",
                "schema_version",
            ],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_job_evaluations_candidate_fingerprint"),
            ["candidate_fingerprint"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_job_evaluations_decision"), ["decision"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_evaluations_degraded"), ["degraded"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_job_evaluations_is_current"), ["is_current"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_evaluations_job_content_hash"), ["job_content_hash"], unique=False
        )
        batch_op.create_index(
            "ix_job_evaluations_job_current", ["job_id", "is_current"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_job_evaluations_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_evaluations_model"), ["model"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_job_evaluations_prompt_version"), ["prompt_version"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_evaluations_rank_score"), ["rank_score"], unique=False
        )

    op.create_table(
        "user_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("predicted_decision", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["job_evaluations.id"],
            name=op.f("fk_user_feedback_evaluation_id_job_evaluations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_user_feedback_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_feedback")),
    )
    with op.batch_alter_table("user_feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_feedback_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_feedback_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_user_feedback_job", ["job_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_feedback_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_feedback_reason"), ["reason"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_feedback_reason"))
        batch_op.drop_index(batch_op.f("ix_user_feedback_job_id"))
        batch_op.drop_index("ix_user_feedback_job")
        batch_op.drop_index(batch_op.f("ix_user_feedback_created_at"))
        batch_op.drop_index(batch_op.f("ix_user_feedback_action"))

    op.drop_table("user_feedback")
    with op.batch_alter_table("job_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_evaluations_rank_score"))
        batch_op.drop_index(batch_op.f("ix_job_evaluations_prompt_version"))
        batch_op.drop_index(batch_op.f("ix_job_evaluations_model"))
        batch_op.drop_index(batch_op.f("ix_job_evaluations_job_id"))
        batch_op.drop_index("ix_job_evaluations_job_current")
        batch_op.drop_index(batch_op.f("ix_job_evaluations_job_content_hash"))
        batch_op.drop_index(batch_op.f("ix_job_evaluations_is_current"))
        batch_op.drop_index(batch_op.f("ix_job_evaluations_degraded"))
        batch_op.drop_index(batch_op.f("ix_job_evaluations_decision"))
        batch_op.drop_index(batch_op.f("ix_job_evaluations_candidate_fingerprint"))
        batch_op.drop_index("ix_job_evaluations_cache")

    op.drop_table("job_evaluations")
    with op.batch_alter_table("candidate_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_preferences_dimension"))

    op.drop_table("candidate_preferences")
    # ### end Alembic commands ###
