"""Keyword tables for classification, in Bulgarian and English.

Kept as data (not code) so the classifier stays small and these can be tuned
without touching logic.
"""

from __future__ import annotations

from jobhunter.domain.enums import Seniority

# --------------------------------------------------------------------- tech ---

PROGRAMMING_LANGUAGES = frozenset(
    {
        "python",
        "java",
        "javascript",
        "typescript",
        "php",
        "c#",
        "c++",
        "c",
        "go",
        "golang",
        "rust",
        "ruby",
        "kotlin",
        "swift",
        "scala",
        "perl",
        "objective-c",
        "dart",
        "elixir",
        "haskell",
        "clojure",
        "r",
        "matlab",
        "vb.net",
        "delphi",
        "cobol",
        "abap",
        "groovy",
        "lua",
        "verilog",
        "vhdl",
        "solidity",
        "bash",
        "shell",
        "powershell",
        "sql",
        "plsql",
        "t-sql",
    }
)

FRAMEWORKS = frozenset(
    {
        "laravel",
        "symfony",
        "codeigniter",
        "yii",
        "zend",
        "django",
        "flask",
        "fastapi",
        "pyramid",
        "spring",
        "spring boot",
        "hibernate",
        "quarkus",
        "react",
        "reactjs",
        "react.js",
        "angular",
        "angularjs",
        "vue",
        "vue.js",
        "vuejs",
        "svelte",
        "next.js",
        "nextjs",
        "nuxt",
        "node.js",
        "nodejs",
        "express",
        "express.js",
        "nestjs",
        "asp.net",
        ".net",
        ".net core",
        "dotnet",
        "blazor",
        "rails",
        "ruby on rails",
        "flutter",
        "react native",
        "ionic",
        "xamarin",
        "qt",
        "electron",
        "jquery",
        "bootstrap",
        "tailwind",
        "tailwindcss",
        "livewire",
        "inertia",
        "alpine.js",
        "htmx",
        "backbone",
        "ember",
        "gatsby",
        "astro",
        "remix",
        "solidjs",
        "phoenix",
    }
)

DATABASES = frozenset(
    {
        "mysql",
        "mariadb",
        "postgresql",
        "postgres",
        "sqlite",
        "oracle",
        "sql server",
        "mssql",
        "mongodb",
        "redis",
        "cassandra",
        "elasticsearch",
        "dynamodb",
        "couchdb",
        "neo4j",
        "influxdb",
        "clickhouse",
        "snowflake",
        "bigquery",
        "redshift",
        "firebase",
        "supabase",
        "cosmos db",
        "db2",
    }
)

TOOLS_AND_PLATFORMS = frozenset(
    {
        "docker",
        "kubernetes",
        "k8s",
        "jenkins",
        "gitlab",
        "github",
        "bitbucket",
        "git",
        "svn",
        "terraform",
        "ansible",
        "puppet",
        "chef",
        "vagrant",
        "aws",
        "azure",
        "gcp",
        "google cloud",
        "digitalocean",
        "heroku",
        "nginx",
        "apache",
        "linux",
        "unix",
        "windows server",
        "bash",
        "jira",
        "confluence",
        "trello",
        "figma",
        "webpack",
        "vite",
        "babel",
        "npm",
        "yarn",
        "composer",
        "maven",
        "gradle",
        "pytest",
        "junit",
        "selenium",
        "cypress",
        "playwright",
        "postman",
        "swagger",
        "graphql",
        "rest",
        "restful",
        "soap",
        "grpc",
        "rabbitmq",
        "kafka",
        "celery",
        "prometheus",
        "grafana",
        "datadog",
        "sentry",
        "splunk",
        "elk",
        "ci/cd",
        "cicd",
        "devops",
        "microservices",
        "api",
        "sass",
        "scss",
        "less",
        "html",
        "css",
        "html5",
        "css3",
        "xml",
        "json",
        "yaml",
        "etl",
        "fpga",
    }
)

ALL_TECH_KEYWORDS = PROGRAMMING_LANGUAGES | FRAMEWORKS | DATABASES | TOOLS_AND_PLATFORMS

# --------------------------------------------------------------------- roles ---

IT_ROLE_KEYWORDS = frozenset(
    {
        # English
        "developer",
        "programmer",
        "software engineer",
        "engineer",
        "architect",
        "full stack",
        "fullstack",
        "full-stack",
        "frontend",
        "front-end",
        "front end",
        "backend",
        "back-end",
        "back end",
        "web developer",
        "mobile developer",
        "android developer",
        "ios developer",
        "qa",
        "quality assurance",
        "tester",
        "test engineer",
        "sdet",
        "devops",
        "sre",
        "site reliability",
        "sysadmin",
        "system administrator",
        "database administrator",
        "dba",
        "data engineer",
        "data scientist",
        "data analyst",
        "machine learning",
        "ml engineer",
        "ai engineer",
        "security engineer",
        "cybersecurity",
        "penetration tester",
        "cloud engineer",
        "network engineer",
        "it support",
        "helpdesk",
        "help desk",
        "technical support",
        "scrum master",
        "product owner",
        "ui/ux",
        "ux designer",
        "ui designer",
        "web designer",
        "technical lead",
        "tech lead",
        "cto",
        "software",
        "it specialist",
        "it team lead",
        "team lead",
        "it manager",
        "it team",
        "solution architect",
        "systems engineer",
        "platform engineer",
        "wordpress",
        "webmaster",
        "it consultant",
        "release engineer",
        "integration engineer",
        "automation engineer",
        "embedded",
        "firmware",
        "hardware engineer",
        "verification engineer",
        # Bulgarian
        "разработчик",
        "програмист",
        "софтуерен",
        "софтуер",
        "инженер",
        "уеб разработчик",
        "уеб дизайнер",
        "тестер",
        "системен администратор",
        "мрежов администратор",
        "бази данни",
        "информационни технологии",
        "техническа поддръжка",
        "ит специалист",
        "анализатор на данни",
    }
)

# Roles that superficially look technical but are not IT positions.
NON_IT_MARKERS = frozenset(
    {
        "шофьор",
        "driver",
        "продавач",
        "продавач-консултант",
        "касиер",
        "готвач",
        "сервитьор",
        "камериерка",
        "чистач",
        "хигиенист",
        "строител",
        "заварчик",
        "електротехник",
        "монтажник",
        "механик",
        "медицинска сестра",
        "лекар",
        "фармацевт",
        "учител",
        "възпитател",
        "счетоводител",
        "юрист",
        "адвокат",
        "охранител",
        "склададжия",
        "оператор на машина",
        "шивач",
        "барман",
        "рецепционист",
        "sales representative",
        "sales manager",
        "call center agent",
        "warehouse",
        "cleaner",
        "waiter",
        "cook",
        "nurse",
        "accountant",
        "мениджър продажби",
        "търговски представител",
    }
)

# --------------------------------------------------------------- seniority ---

# Ordered most-specific first; the classifier stops at the first family that hits.
SENIORITY_PATTERNS: list[tuple[Seniority, tuple[str, ...]]] = [
    (
        Seniority.INTERNSHIP,
        (
            "intern",
            "internship",
            "стаж",
            "стажант",
            "стажантска",
            "практика",
            "практикант",
            "trainee programme",
        ),
    ),
    (
        Seniority.ENTRY,
        (
            "entry level",
            "entry-level",
            "начално ниво",
            "без опит",
            "no experience",
            "без предишен опит",
            "graduate",
            "завършил",
            "trainee",
            "стажантска програма",
            "школа",
            "academy",
            "академия",
            "0-1 years",
            "0 to 1",
            "0-2 years",
        ),
    ),
    (
        Seniority.JUNIOR,
        (
            "junior",
            "младши",
            "начинаещ",
            "jr.",
            "jr ",
            "юниър",
            "1-2 years",
            "1 to 2",
            "up to 2 years",
            "до 2 години",
            "малък опит",
            "малко опит",
        ),
    ),
    (
        Seniority.JUNIOR_MID,
        ("junior/mid", "junior to mid", "младши/среден", "2-3 years", "2 to 3"),
    ),
    (
        Seniority.MID,
        (
            "mid-level",
            "mid level",
            "midlevel",
            "middle",
            "среден",
            "среден специалист",
            "intermediate",
            "associate",
            "regular",
            "3-4 years",
            "3 to 4",
            "2-4 years",
        ),
    ),
    (
        Seniority.MID_SENIOR,
        ("mid/senior", "mid to senior", "среден/старши", "4-6 years"),
    ),
    (
        Seniority.SENIOR,
        (
            "senior",
            "старши",
            "sr.",
            "sr ",
            "сениър",
            "опитен",
            "5+ years",
            "5 or more",
            "над 5 години",
            "experienced",
            "expert",
            "експерт",
        ),
    ),
    (
        Seniority.LEAD,
        (
            "lead",
            "team lead",
            "tech lead",
            "technical lead",
            "principal",
            "staff engineer",
            "ръководител",
            "водещ",
            "head of",
            "manager",
            "мениджър",
            "architect",
            "архитект",
            "director",
            "директор",
            "chief",
        ),
    ),
]

# Jobs.bg exposes its own level taxonomy; these are the exact site strings.
SITE_LEVEL_MAP: dict[str, Seniority] = {
    "entry-level": Seniority.ENTRY,
    "entry level": Seniority.ENTRY,
    "начално ниво": Seniority.ENTRY,
    "junior": Seniority.JUNIOR,
    "junior-level": Seniority.JUNIOR,
    "младши": Seniority.JUNIOR,
    "mid-level": Seniority.MID,
    "mid level": Seniority.MID,
    "среден": Seniority.MID,
    "senior-level": Seniority.SENIOR,
    "senior level": Seniority.SENIOR,
    "старши": Seniority.SENIOR,
    "experienced": Seniority.SENIOR,
    "lead": Seniority.LEAD,
    "ръководител": Seniority.LEAD,
}

# ------------------------------------------------------------- requirements ---

REQUIRED_SECTION_MARKERS = (
    "изисквания",
    "изисква се",
    "задължителни",
    "необходими",
    "търсим",
    "какво очакваме",
    "profile",
    "requirements",
    "must have",
    "must-have",
    "required",
    "qualifications",
    "what you bring",
    "what we expect",
    "you have",
    "you should have",
)

PREFERRED_SECTION_MARKERS = (
    "предимство",
    "предимства",
    "ще се счита за предимство",
    "плюс",
    "би било предимство",
    "nice to have",
    "nice-to-have",
    "preferred",
    "advantage",
    "bonus",
    "would be a plus",
    "desirable",
    "optional",
)

RESPONSIBILITY_MARKERS = (
    "отговорности",
    "задължения",
    "ще се занимавате",
    "responsibilities",
    "what you will do",
    "your role",
    "duties",
    "основни задачи",
)

LANGUAGE_REQUIREMENT_MARKERS = {
    "english": ("english", "английски"),
    "german": ("german", "немски", "deutsch"),
    "french": ("french", "френски"),
    "spanish": ("spanish", "испански"),
    "italian": ("italian", "италиански"),
    "russian": ("russian", "руски"),
    "bulgarian": ("bulgarian", "български"),
}

EDUCATION_MARKERS = (
    "висше образование",
    "бакалавър",
    "магистър",
    "университет",
    "bachelor",
    "master",
    "degree",
    "university",
    "phd",
    "доктор",
)


# The language names Jobs.bg puts in its own "language" field, mapped to the
# names a candidate profile uses. This field is the site's own structured data
# and is far more reliable than looking for language names in the posting body.
SITE_LANGUAGE_NAMES: dict[str, str] = {
    "английски": "english",
    "немски": "german",
    "френски": "french",
    "испански": "spanish",
    "италиански": "italian",
    "португалски": "portuguese",
    "гръцки": "greek",
    "турски": "turkish",
    "руски": "russian",
    "български": "bulgarian",
    "румънски": "romanian",
    "полски": "polish",
    "нидерландски": "dutch",
    "шведски": "swedish",
    "чешки": "czech",
    "унгарски": "hungarian",
}
